# site settings
title: Portfolio
subtitle: by Aliza Samad
email: alizasamad@ucsb.edu
description: Welcome to my Data Analysis Portfolio
#baseurl: # the subpath of your site, e.g. /blog
url: https://alizasamad.github.io # the base hostname & protocol for your site
author: Aliza Samad
#street_address: 1234 Somewhere Road
city: San Francisco Bay Area
state: CA
#zip_code: 55555
country: United States of America
phone: (925) 495-9396

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/alizasamad
  #GitLab:
  #Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  #Instagram: _al._.iza_
  LinkedIn: https://www.linkedin.com/in/aliza-samad-data-analyst/
  #Twitter: https://twitter.com/andrewbanchich
  #Facebook:
  #Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
