name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: helaili/jekyll-action@2.4.0
        build_only: true
