name: Fetch Blog Posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  fetch-blogs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch blog posts
      run: |
        mkdir -p blogs
        curl -L https://github.com/alizasamad/blogs/blob/main/Blog%231.md -o blogs/Blog1.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add blogs/*.md
        git commit -
